# -*- coding: utf-8 -*-
"""M15-app1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mFhDmueoGCM65gGJbKPIitr6E4Ej7xzv
"""

import streamlit as st
import pandas as pd
import numpy as np

# Título do App
st.title("Meu Primeiro Projeto no Streamlit")

# Boas-vindas
st.write('Bem-vindos')

# Descrição
st.write("Este é meu primeiro app criado com Streamlit Cloud!")

# Um exemplo de DataFrame
# Tabela interativa
# Dados iniciais com horários
data = {
    'Nomes': ['Alice', 'Bob', 'Carlos', 'Diana'],
    'Idades': [25, 30, 35, 40],
    'Pontuações': [90, 85, 78, 92],
    'Latitude': [37.7749, 34.0522, 40.7128, 51.5074],  # Coordenadas fictícias
    'Longitude': [-122.4194, -118.2437, -74.0060, -0.1278],
    'Horário': ['08:00', '09:30', '14:15', '16:45']  # Exemplos de horários
}

st.write("Aqui está uma tabela de exemplo:")
st.dataframe(data)

# Slider interativo
idade_minima = st.slider("Filtrar pela idade mínima:", 20, 50, 25)
st.write(f"Idade mínima selecionada: {idade_minima}")
st.write("Tabela filtrada:")
st.dataframe(data[data['Idades'] >= idade_minima])

# Gráfico simples
grafico_data = np.random.randn(50, 2)
st.write("Gráfico gerado aleatoriamente:")
st.line_chart(grafico_data)

# Criando um mapa com as coordenadas fictícias
st.map(df[['Latitude', 'Longitude']])

# Mostrando os dados na aplicação
st.title("Mapa Interativo de Pessoas")
st.write("Dados das pessoas com suas localizações:")
st.dataframe(df)

# Criando o mapa
st.map(df[['Latitude', 'Longitude']])

# Criando botões
if st.button("Clique aqui!"):
    st.write("Você clicou no botão!")

