# -*- coding: utf-8 -*-
"""M15-app1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mFhDmueoGCM65gGJbKPIitr6E4Ej7xzv
"""

import streamlit as st
import pandas as pd
import numpy as np

# Título do App
st.title("Meu Primeiro Projeto no Streamlit")

# Descrição
st.write("Este é meu primeiro app criado com Streamlit Cloud!")

# Tabela interativa
data = pd.DataFrame({
    'Nomes': ['Alice', 'Bob', 'Carlos', 'Diana'],
    'Idades': [25, 30, 35, 40],
    'Pontuações': [90, 85, 78, 92]
})
st.write("Aqui está uma tabela de exemplo:")
st.dataframe(data)

# Slider interativo
idade_minima = st.slider("Filtrar pela idade mínima:", 20, 50, 25)
st.write(f"Idade mínima selecionada: {idade_minima}")
st.write("Tabela filtrada:")
st.dataframe(data[data['Idades'] >= idade_minima])

# Gráfico simples
grafico_data = np.random.randn(50, 2)
st.write("Gráfico gerado aleatoriamente:")
st.line_chart(grafico_data)